module.exports.usernames = [
    'Adam Erwin',
    'Adeline Elwell',
    'Aidan Cedillo',
    'Alanna Ogden',
    'Alia Davey',
    'Alison Dudley',
    'Alvin Gibbons',
    'Anabella Lash',
    'Aniya Noel',
    'Arian Hopkins',
    'Arnav Reber',
    'Bennett Goodin',
    'Blair Backus',
    'Brantley Houk',
    'Braxton Frisby',
    'Cannon Lu',
    'Cash Eaves',
    'Coco Crocker',
    'Collin Vargo',
    'Conner Music',
    'Dallas Kline',
    'Edwin Harbin',
    'Elianna Freed',
    'Emory Valdivia',
    'Erik Luis',
    'Ford Bartlett',
    'Gavin Foley',
    'Grant Groff',
    'Hallie Fuentes',
    'Hayes Cade',
    'Isla Huff',
    'Jaime Aponte',
    'Jaime Roof',
    'Jayleen Hilton',
    'Jazlynn Tinker',
    'Jet Rollins',
    'Joe Babineaux',
    'Jonah Calderon',
    'Kaia Cortez',
    'Kaylynn Holzer',
    'Kobe Hanes',
    'Kylee Bartz',
    'Kylie Link',
    'Kylie Schulman',
    'Lexi Lankford',
    'Lexie Bateman',
    'Lia Hoagland',
    'Libby Zeigler',
    'Liliana Damron',
    'Little Reinke',
    'Lucas Barrier',
    'Maddie Mulvey',
    'Maria Roark',
    'Maxine Benham',
    'Melody Waller',
    'Monroe Mchugh',
    'Myah Adamson',
    'Myles Close',
    'Ollie Cyrus',
    'Omar Peeler',
    'Philip Toscano',
    'Regina Mcabee',
    'Rhea Deberry',
    'Rhys Hundley',
    'Saige Furlong',
    'Samuel Harper',
    'Simon Beale',
    'Sloan Merryman',
    'Sophie Dearing',
    'Tanner Miner',
    'Teagan Eads',
    'Tony Coles',
    'Violet Munguia',
    'Zac Mertz',
    'Zachary Lang',
    'Zack Matteson',
    'Zoie Thibeault',
    "Adalyn Knotts",
    "Adriel Oconnor",
    "Colt Seifert",
    "Conrad Wolfe",
    "Darren Graf",
    "Ellis Hartmann",
    "Everly Vernon",
    "Helen Ladd",
    "Hudson Hake",
    "Kendall Linton",
    "Lisa Whitmire",
    "Little Bromley",
    "Nickolas Patel",
    "Noa Montez",
    "Orion Silvas",
    "Rex Montalvo",
    "Ricky Bowden",
    "Rosa Jemison",
    "Tate Gayton",
    "Toby Dear",
    "Wyatt Lackey",
    "Xavier Legg",
    "Amaya Abbey"
]

module.exports.sillyUsernames = [
    'shaquille.oatmeal',
    'Hanging_with_my_gnomies',
    'hoosier-daddy',
    'fast_and_the_curious',
    'averagestudent',
    'BadKarma',
    'google_was_my_idea',
    'cute.as.ducks',
    'casanova',
    'real_name_hidden',
    'airyPoppins',
    'dora_the_explorer',
    'OP_rah',
    'YellowSnowman',
    'Joe Not Exotic',
    'username_copied',
    'whos_ur_buddha',
    'unfinished_sentenc',
    'AllGoodNamesRGone',
    'Something',
    'me_for_president',
    'tinfoilhat',
    'oprahwindfury',
    'anonymouse',
    'Definitely_not_an_athlete',
    'HeartTicker ',
    'YESIMFUNNY',
    'BenAfleckIsAnOkActor',
    'Magicschoolbusdropout',
    'Everybod',
    'regina_phalange',
    'PawneeGoddess',
    'pluralizes_everythings',
    'chickenriceandbeans',
    'test_name_please_ignore',
    'IYELLALOT',
    'heyyou',
    'laugh_till_u_pee',
    'aDistraction',
    'crazy_cat_lady',
    'nana_hammock',
    'Thegodfatherpart4',
    'unfriendme',
    'babydoodles',
    'fluffycookie',
    'buh-buh-bacon',
    'ashley_said_what',
    'LactoseTheIntolerant',
    'ManEatsPants',
    'Twentyfourhourpharmacy',
    'plebottomjeans',
    'Babushka',
    'toastedbagelwithcreamcheese',
    'baeconandeggz',
    'FartinLutherKing',
    'coolshirtbra',
    'kentuckycriedfricken',
    'REVERANDTOAST',
    'kim_chi',
    'idrinkchocolatemilk',
    'intBroseph',
    'chin_chillin',
    'ghostfacegangsta',
    'bigfootisreal',
    'santas_numbe',
    'thehornoftheunicorn',
    'iNeed2P.',
    'abductedbyaliens',
    'actuallynotchrishemsworth',
    'chocheesefriePersonallyvictimizedbyreginageorge',
    'just-a-harmless-potato',
    'FrostedCupcake',
    'Avocadorable',
    'fatBatman',
    'quailandduckeggs',
    'PaniniHead',
    'mandymooressingingvoice',
    'catsordogs',
    'fartnRoses',
    'RedMonkeyButt',
    'FreddyMercurysCat',
    'MasterCheif',
    'FreeHugz',
    'ima.robot',
    'actuallythedog',
    'notthetigerking',
    'pixie_dust',
    'ChopSuey',
    'urkey_sandwich',
    'B.Juice',
    'Chris_P_Bacon',
    'LtDansLegs',
    'WookiesrPpl2',
    'hogwartsfailure',
    'CourtesyFlush',
    'MomsSpaghetti',
    'spongebobspineapple',
    'garythesnail',
    'nothisispatrick',
    'CountSwagula',
    'SweetP',
    'PNUT',
    'Snax',
    'Nuggetz',
    'colonel_mustards_rope',
    'baby_bugga_boo',
    'joancrawfordfanclub',
    'fartoolong',
    'loliateyourcat',
    'rawr_means_iloveyou',
    'ihavethingstodo.jpg',
    'heresWonderwall ',
    'UFO_believer',
    'ihazquestion',
    'SuperMagnificentExtreme',
    'It’s_A _Political_ Statement',
    'TheAverageForumUser',
    'Just_a_teen',
    'OmnipotentBeing',
    'GawdOfROFLS',
    'loveandpoprockz',
    '2_lft_feet',
    'Bread Pitt',
    'Rejectedbachelorcontestant',
    'Schmoople',
    'LOWERCASE GUY',
    'Unnecessary',
    'joan_of_arks_angel',
    'InstaPrincess',
    'DroolingOnU',
    'Couldnt_Find_Good_Name',
    'AngelWonderland',
    'Born-confused',
    'SargentSaltNPepa',
    'DosentAnyoneCare',
    'quaratineinthesejeans',
    'thanoslefthand',
    'ironmansnap',
    'halametbmybae',
    'eterparkerspuberty',
    'severusvape',
    'theotherharrypotter',
    'GrangerDanger',
    'BlueIvysAssistant',
    'Ariana_Grandes_Ponytail',
    'HotButteryPopcorn',
    'MelonSmasher',
    'morgan_freeman_but_not',
    'potatoxchipz',
    'oxtrotTangoLove',
    'ElfishPresley',
    'WustacheMax',
    'JuliusSeizure',
    'HeyYouNotYouYou',
    'OneTonSoup',
    'HoneyLemon',
    'LoveMeKnot',
    'Bud Lightyear',
    'takenbyWine',
    'aking0ver',
    'Unic0rns',
    'in_jail_out_soon',
    'hotgirlbummer',
    'behind_you',
    'itchy_and_scratchy',
    'not_james_bond',
    'a_collection_of_cells',
    'CowabungaDude',
    'TeaBaggins',
    'intelligent_zombie',
    'imma_rage_quit',
    'kiss-my-axe',
    'king_0f_dairy_queen',
    'desperate_enuf',
    'AirisWindy',
    'cheeseinabag',
    'MakunaHatata',
    'rambo_was_real',
    'churros4eva',
    'namenotimportant',
    'i_boop_ur_nose',
    'image_not_uploaded',
    'suck_my_popsicle',
    'sofa_king_cool',
    'RootinTootinPutin',
    'blousesandhouses',
    'iblamejordan',
    'manic_pixie_meme_ gir',
    'Technophyle',
    'Cuddly-Wuddly',
    'JesusoChristo',
    'peap0ds',
    'whats_ur_sign',
    'TheMilkyWeigh',
    'BabyBluez',
    'BarbieBreath',
    'MangoGoGo',
    'DirtBag',
    'FurReal',
    'ScoobyCute',
    'YouIntradouchingMyshelf',
    'IwasReloading',
    'WellEndowedPenguin',
    'TheAfterLife',
    'PuppiesnKittens',
    'WakeAwake',
    'Coronacosmo',
    'wherearetheavocados',
    'ijustwanttobeme',
    'TheKidsCallMeBoss',
    'SewerSquirrel',
    'because.i.like.to.like',
    'friedchocolate',
    'DonWorryItsGonBK',
    'Early_Morning_Coffee',
    'drunkbetch',
    'strawberry_pineapple',
    'MissPiggysDimples',
    'chickenbaconranchpizza',
    'cereal_killer',
    'khaleesisfourthdragon',
    'darth.daenerys',
    'LeslieKnopesBinder',
    'BettyBoopsBoop',
    'Freddie_Not_The_Fish',
    'Billys_Mullet',
    'Calzone_Zone',
    'ChickyChickyParmParm',
    'Adobo_Ahai',
    'theoldRazzleDazzle',
    'Not-Insync',
    'Toiletpaperman',
    'Reese WitherFork',
    'LizzosFlute',
    'Macauliflower Culkin',
    'Llama del Rey',
    'Hot Name Here',
    'Carmelpoptart',
    'notfunnyatall',
    'Mangonificent',
    'toastcrunch',
    'fizzysodas',
    'kokonuts',
    'cherry-picked'
]
